<template>
	<section>
		<h3>导航</h3>
		<p>不同类型的内容的入口</p>

		<br>
		<table>
			<tr>
				<th width="120px">Name</th>
				<th>Description</th>
			</tr>
			<tr>
				<td>tabbar</td>
				<td>置于底部为一级导航，置于顶部为二级导航</td>
			</tr>
			<tr>
				<td>drawer</td>
				<td>抽屉式导航</td>
			</tr>
			<tr>
				<td>grid</td>
				<td>宫格或阵列式导航</td>
			</tr>
			<tr>
				<td>breadcrumb</td>
				<td>面包屑导航</td>
			</tr>
		</table>
	</section>
</template>